function AiDisclaimer({ className = '', showSources = false }) {
  return (
    <div className={`bg-yellow-50 border border-yellow-200 rounded-lg p-3 text-sm ${className}`}>
      <div className="flex items-start gap-2">
        <svg className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <div className="text-yellow-800">
          <p className="font-medium">AI-Generated Analysis</p>
          <p className="text-yellow-700 mt-1">
            This analysis was generated by AI and may contain errors. Always verify sources before drawing conclusions.
          </p>
          {showSources && (
            <p className="text-yellow-600 mt-1 text-xs">
              Sources: CA Legislature roll call votes, official campaign websites, verified social media accounts, and news publications.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

export default AiDisclaimer;